### ISSUE TITLE
フロントエンドの再実装（ファイルアップロード）

### ISSUE THREAD

**Issue by tasksk8** [AIIT-Oikawa-PBL-2024/AI-Notebook#165]
## 概要

ファイルアップロードの再実装とそれに付随するバックエンドの機能追加

### 何をやるのか
ファイルアップロードの再実装とそれに付随するバックエンドの機能追加

### なぜやるのか
Frontendの再実装のため

## 受入条件

- [ ] ファイルアップロード機能が実装されていること
- [ ] 共通レイアウト作成の完了
- [ ] 署名付きURLの実装完了（ファイル名の濁点など[ナントカ正規化]はバックエンドの処理と一致させる）

## タスク

- [ ] タスク1
- [ ] タスク2

## その他

署名付きURLの参考情報
https://cloud.google.com/storage/docs/access-control/signed-urls?hl=ja
https://zenn.dev/tbsten/articles/a05e2ff7f2a460

**Comment by sayzkkgw** [comment]
close
